baseURL = "https://andys.page/"
languageCode = "en-us"
author = "Andy Salerno"
title = "⌨️🤷🏻‍♂️📷"
theme = "mytheme"
enableEmoji = true
hasCJKLanguage = false
pygmentsUseClasses = true
pygmentsCodeFences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[params]
  sitename = "Andy, xor Andrew"
  tagline = "Professional software developer / hobbyist street photographer"
  faviconfile = "images/favicon.png"
  highlightjs = false
  highlightjslanguages = ["rust"]
  progressively = false

[[menu.primary]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.primary]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.primary]]
    name = "Reading List"
    url = "/readinglist/"
    weight = 3
[[menu.primary]]
    name = "GitHub"
    url = "https://github.com/andysalerno"
    weight = 4
[[menu.primary]]
    name = "Flickr"
    url = "https://www.flickr.com/photos/andysalerno/"
    weight = 6
[[menu.primary]]
    name = "Rss (there are dozens of us!)"
    url = "/index.xml"
    weight = 7

[caches]
  [caches.images]
    dir = ':cacheDir/images'